name: 🌟 Feature Request
description: Запит на нову можливість або покращення функціоналу
labels: [enhancement, suggestion]
body:
  - type: markdown
    attributes:
      value: |
        Дякуємо за ідею! Заповніть поля нижче, щоб краще зрозуміти вашу пропозицію.
  - type: input
    id: title
    attributes:
      label: Коротка назва фічі

      placeholder: 'Наприклад: "Додати автосейв у форму"'

    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Що це має робити?
      description: Опишіть поведінку чи функціонал, який ви пропонуєте
  - type: textarea
    id: value
    attributes:
      label: Яку проблему це вирішує або яку користь дає?
  - type: textarea
    id: implementation
    attributes:
      label: Ідеї щодо реалізації (необов’язково)

      placeholder: Можна згадати існуючі компоненти, API, тощо

