name: 💬 Пропозиція / Обговорення
description: Тема для командної дискусії щодо рішень, які впливають на проєкт
labels: [discussion, question, proposal]
body:
  - type: markdown
    attributes:
      value: |

        Якщо у тебе є ідея або сумнів щодо технічного рішення - опиши її тут. Це допоможе проговорити все в одному місці й зберегти хронологію рішень.

  - type: input
    id: topic
    attributes:
      label: Коротка тема

      placeholder:
        'Наприклад: "Пропозиція перейти на Zustand замість Redux Toolkit"'

    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Контекст або передумови
      description: Чому виникла ця тема? Що стало тригером?
  - type: textarea
    id: proscons
    attributes:
      label: Плюси та мінуси

      description: Якщо можливо - вкажи аргументи за і проти

  - type: textarea
    id: suggestions
    attributes:
      label: Що ти пропонуєш?
      description: Твоя ідея або бажаний варіант рішення
  - type: textarea
    id: questions
    attributes:
      label: Питання до команди

      description: Що конкретно потребує обговорення?

